name: Build
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - name: Build and package
        run: |
          npm i
          npm run build
          npm run package
      - name: Publish to 'latest' branch
        run: |
          git config --global user.name "Yakov Lipkovich"
          git config --global user.email 'no@no'
          git checkout -b latest
          git add -f dist
          git commit -m "Automatically create release"
          git push -f --set-upstream origin latest
